
---
- name: Proje2-Team Uygulaması Kurulumu
  hosts: webservers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
        - python3-pip
        - python3-dev
        - default-libmysqlclient-dev

    - name: Clone repository
      git:
        repo: "https://@github.com/Herr-Aksoy/Proje2-Team.git"
        dest: "/home/ubuntu/Proje2-Team"

    - name: Install Python requirements
      pip:
        requirements: "/home/ubuntu/Proje2-Team/requirements.txt"

    - name: Run manage.py commands
      command: "{{ item }}"
      args:
        chdir: "/home/ubuntu/Proje2-Team/src"
      loop:
        - "python3 manage.py collectstatic --noinput"
        - "python3 manage.py makemigrations"
        - "python3 manage.py migrate"
        - "python3 manage.py runserver 0.0.0.0:80"







# ---
# - name: Proje2-Team Uygulaması Kurulumu
#   hosts: webservers
#   become: true

#   tasks:
#     - name: Update apt cache
#       apt:
#         update_cache: yes

#     - name: Install necessary packages
#       apt:
#         name: "{{ item }}"
#         state: present
#       loop:
#         - git
#         - python3
#         - python3-pip
#         - python3-dev
#         - default-libmysqlclient-dev

#     - name: Clone repository
#       git:
#         repo: "https://@github.com/Herr-Aksoy/Proje2-Team.git"
#         dest: "/home/ubuntu/Proje2-Team"

#     - name: Install Python requirements
#       pip:
#         requirements: "/home/ubuntu/Proje2-Team/requirements.txt"

#     - name: Run manage.py commands
#       command: "{{ item }}"
#       args:
#         chdir: "/home/ubuntu/Proje2-Team/src"
#       loop:
#         - "python3 manage.py collectstatic --noinput"
#         - "python3 manage.py makemigrations"
#         - "python3 manage.py migrate"
#         - "python3 manage.py runserver 0.0.0.0:80"










